config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :patients
  devise_for :users
  resources :doctors
  resources :patients
  resources :appointments

  get 'search_doc' => "patients#search"
  get 'reject' => "doctors#reject"
  get 'accept' => "doctors#accept"
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_scope :patient do
      get 'patients/sign_out' => "devise/sessions#destroy"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :person_name
  belongs_to :wek
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments

end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :appointments
end

app/models/people.rb
class People < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/person_name.rb
class PersonName < ApplicationRecord
	has_many :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/wek.rb
class Wek < ApplicationRecord
	belongs_to :doctor
	has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_destroy_user_session_path(resource_or_scope)
	    if resource_or_scope == :user
	      new_user_session_path
	    end
	  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
		before_action :authenticate_patient!

	def new
		@appointment = Appointment.new
	end

	def create
		@doc = params[:doctor_id]
		@wek = params[:wek_id]
		@peron = params[:person_name_id]
		@patient = current_patient.id
		@appointment = Appointment.new(:doctor_id => @doc, :wek_id => @wek,:person_name_id => @peron, :patient_id => @patient)
    respond_to do |format|
			if !Appointment.where(:doctor_id => @doc, :wek_id => @wek, :person_name_id => @peron).present?
	      if @appointment.save
	        format.html { redirect_to appointments_path, notice: 'appointment was successfully created.' }
	        format.json { render :show, status: :created, location: @appointment }
			end
	      else
	        format.html { render :new }
	        format.json { render json: appointments_path.errors, status: :unprocessable_entity }
	      end
    end
	end
	def destroy
		@appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path, notice: 'product delete successfully'
  end

	def index
		@appointment = Appointment.all
	end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	before_action :authenticate_user!

	def index 
		@appointment = Appointment.all
		@doctor= Doctor.where(:start_time => "10:00", :end_time => "13:00")
		@doc = Doctor.where(:start_time => "15:00", :end_time => "19:00")
	end

	def new
		@wek = Wek.all
		@doctor = Doctor.new
	end

	def show 
	end

	def create
		@wek = Wek.all
		@doctor = Doctor.new(doctor_params.merge(user_id: current_user))
    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'slot was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
	end

	def reject
		 @ap = Appointment.where(:id => params[:id] ,:is_select => params[:appointment]).update(:is_select => true)
   		 redirect_to doctors_path
	end
	def accept
		@ap = Appointment.where(:id => params[:id] ,:is_select => params[:appointment]).update(:is_select => false)
		redirect_to doctors_path
	end

	def doctor_params
		params.require(:doctor).permit(:start_time, :end_time,:user_id,:not_available,:wek_id,:name)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	before_action :authenticate_patient!

	def new
		if params[:doctor_select].present?
			redirect_to "search"
		end
		@doc_id = [:doc_id]
	end

	def index
		@doctor = Doctor.all
	end

	def search
		 @product = appointments.build(:doctor_id => params[:person_name].values.map(&:to_i), :wek_id => params[:wek].values.map(&:to_i), :person_name_id =>  params[:person_name].values.map(&:to_i))
		@person = params[:person_name].values.map(&:to_i)
		@doc = params[:select_doc].values.map
		@wek = params[:wek].values.map(&:to_i)
			@appointment = Appointment.create(:doctor_id => @doc, :wek_id => @wek, :person_name_id => @person)
			if @appointment.save
			@doctor_select = params[:doctor_select].values
			@docto_select =Doctor.find(@doctor_select)
	end

	end
	def appointment_params
		params.require(:appointment).permit(:doctor_id, :wek_id,:people_id)
	end
	def show
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
	def doc
		 Doctor.where("id = ?", @docs).select( "start_time")
	end
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<br />
<%= form_with(model: appointment, local: true) do |f| %>
Day:<%= select_tag :wek_id, options_from_collection_for_select(Wek.all, 'id', 'name') %>
Time:<%= select_tag :doctor_id, options_from_collection_for_select(Doctor.all, 'id', 'start_time') %>
Doctor Name:<%= select_tag :person_name_id, options_from_collection_for_select(PersonName.all, 'id', 'name') %>
  <button type="submit" class="btn">Submit</button>
<%end%>

app/views/appointments/edit.html.erb
<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> 

app/views/appointments/index.html.erb
<p>booked appointment</p>
<table border="1">
  <thead>
    <tr>
      <th>Time</th>
      <th>Day</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @appointment.each do |appointment| %>
      <tr>
        <%if appointment.is_select == true%>
          <td><%= appointment.doctor.start_time %></td>
          <td><%= appointment.wek.name %></td>
          <td><%= appointment.person_name.name %></td>
          
          <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
      </tr>
    <% end %>
  </tbody>

  <table border="1">
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <p>panding appointment</p>
    <% @appointment.each do |appointment| %>
      <tr>
        <%if appointment.is_select == false%>
          <td><%= appointment.doctor.start_time %></td>
          <td><%= appointment.wek.name %></td>
          <td><%= appointment.person_name.name %></td>
          <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<%=link_to "Add Appointment" , new_appointment_path%><br/>
<%= link_to 'Logout', destroy_patient_session_path %>

app/views/appointments/new.html.erb
<%= render 'form',appointment: @appointment %>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |f| %>
<table border="1">
	<tr>
		<h3><%= Wek.first.name%></h3>
		<%= f.select :wek_id , options_for_select(@wek.collect{|w|[w.name, w.id]},{includ_blank: 'select day'})%>
			doctor name<%= f.text_field :name %>
			<p>on leave<%=f.check_box :not_available %></p>
			<%= f.hidden_field :user_id, value: current_user.id%>
		<td>
			<p>select start time</p>
				<%= f.select :start_time, ['10:00', '15:00']%>
		</td>
	</tr>
	<tr>
	<td>
			<p>select end time</p>
			<%= f.select :end_time, ['13:00', '19:00']%>
		</td>
	</tr>
	<tr>
	<tr>
		<td>
			<%= submit_tag	 'submit'%>
		</td>
	</tr>
	</table>
<%end%>

app/views/doctors/edit.html.erb
<%= render 'form', doctor: @doctor %>
<%= link_to 'Show', @doctor %> 

app/views/doctors/index.html.erb
<p>booked appointment</p>
<table border="1">
  <thead>
    <tr>
      <th>Time</th>
      <th>Day</th>
      <th>Patient Name</th>
    </tr>
  </thead>
  <tbody>
    <% @appointment.each do |appointment| %>
      <tr>
        <%if appointment.is_select == true%>
          <td><%= appointment.doctor.start_time %></td>
          <td><%= appointment.wek.name %></td>
          <td><%= appointment.patient.name%></td>
          <% @app = appointment.is_select%>
          
          <td><%= link_to 'reject', reject_path(:appointment => @app,:id=>appointment.id)  %></td>
          <%end%>
      </tr>
    <% end %>
  </tbody>


<table border="1">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
        <p>Pending appointment</p>
    <% @appointment.each do |appointment| %>
      <tr>
        <%if appointment.is_select == false%>
          <td><%= appointment.doctor.start_time %></td>
          <td><%= appointment.wek.name %></td>
          <td><%= appointment.patient.name%></td>
          <% @app = appointment.is_select%>
          
          <td><%= link_to 'reject', reject_path(:appointment => @app,:id=>appointment.id)  %></td>
          <td><%= link_to 'accept', accept_path(appointment) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
  <%= link_to 'Logout', destroy_user_session_path %>

app/views/doctors/new.html.erb
<%= render 'form',doctor: @doctor %>

app/views/home/index.html.erb
<h3>login as Doctor</h3>
<%=  link_to "loginn", doctors_path%> 
<h3>login as patient</h3>
<%= link_to "login", appointments_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<p>available time slot</p>


  <%#= select_tag 'doctor_select' , options_for_select(@doctor.collect{|w|[w.name, w.id]} )%>
  <%#= collection_select :doctor_select, Doctor.order(:name).map { |doc| [doc.name, doc.id]}%>

<%= form_tag new_appointment_path  , :method => :get, :class => 'form-search' do %>
  Day:<%= collection_select :wek, :id, Wek.all, :id, :name %>
  Time:<%= collection_select :select_doc, :id, Doctor.all, :id, :start_time%>

  Doctor Name:<%= collection_select :person_name, :id, PersonName.all, :id, :name %>
  <button type="submit" class="btn">Submit</button>
<% end %>

<table>
  <thead>
    <tr>
      <th>Time Slot</th>
    </tr>
  </thead>
  <tbody>
    <% @doctor.each do |doctor| %>
      <tr>
        <%if !doctor.not_available == true%>
          <td><%#= doctor.start_time %></td>
          <td><%#= doctor.end_time %></td>
          <td><%#= doctor.name%></td>
          <%#= link_to "book apointment", new_patient_path(:doc_id =>doctor.id, :doctor_selet => params[:doctor_select])%>
        <%else%>
          <p>doctornot available</p>
        <%end%>
      </tr>
    <% end %>
  </tbody>

<script>
  $(document).ready(function(){

    $("#doctor_select").live("change", function(){
      debugger
      main_cat = $("#doctor_select").val();
    })
  }
</script>

app/views/patients/search.html.erb
<p>available time slot</p>
<%= form_tag search_doc_path  , :method => :get, :class => 'form-search' do %>
  <%= collection_select :wek, :id, Wek.all, :id, :name %>
  <%= collection_select :select_doc, :id, Doctor.all, :id, :start_time%>

  <%= collection_select :person_name, :id, PersonName.all, :id, :name %>
  <button type="submit" class="btn">Submit</button>
<% end %>

<table>
  <thead>
    <tr>
      <th>Time Slot</th>
    </tr>
  </thead>
  <tbody>
    <% @doctor.each do |doctor| %>
      <tr>
        <%if !doctor.not_available == true%>
          <td><%#= doctor.start_time %></td>
          <td><%#= doctor.end_time %></td>
          <td><%#= doctor.name%></td>
          <%#= link_to "book apointment", new_patient_path(:doc_id =>doctor.id, :doctor_selet => params[:doctor_select])%>
        <%else%>
          <p>doctornot available</p>
        <%end%>
      </tr>
    <% end %>
  </tbody>

<script>
  $(document).ready(function(){

    $("#doctor_select").live("change", function(){
      debugger
      main_cat = $("#doctor_select").val();
    })
  }
</script>